services:
  # MongoDB Database
  mongo:
    image: mongo:6.0
    container_name: portal-berita-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: portal-berita
    volumes:
      - mongo-data:/data/db
    networks:
      - portal-berita-network

  # Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: portal-berita-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/portal-berita
      - JWT_SECRET=your-super-secret-jwt-key-for-docker
      - JWT_REFRESH_SECRET=your-refresh-secret-key
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - portal-berita-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portal-berita-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_SOCKET_URL=http://localhost:5000
      - GENERATE_SOURCEMAP=false
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - portal-berita-network

volumes:
  mongo-data:

networks:
  portal-berita-network:
    driver: bridge